apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: manage-nodes
subjects:
- kind: ServiceAccount
  name: developer-ro
  namespace: default
roleRef:
  kind: ClusterRole 
  name: nodes-management
  apiGroup: rbac.authorization.k8s.io
