apiVersion: batch/v1
kind: CronJob
metadata:
  name: moj-cronjob-echo
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template: 
        spec:
          containers:
          - name: echo
            image: busybox
            args: 
            - /bin/sh
            - -c 
            - date; echo "Som CronJob."
          restartPolicy: OnFailure