apiVersion: v1
kind: Pod
metadata:
  name: jablko-app
  labels:
    app: jablko
spec:
  containers:
  - name: jablko-app
    image: hashicorp/http-echo
    args:
      - "-text=jablko"

--- 

apiVersion: v1
kind: Service
metadata:
  name: jablko-service
spec:
  selector:
    app: jablko
  ports:
    - port: 5678