apiVersion: batch/v1
kind: Job
metadata:
  generateName: moj-job-echo-
spec:
#  ttlSecondsAfterFinished: 10
  template:
    spec:
      containers:
      - name: echo
        image: busybox
        command: ["echo"]
        args: ["Som Job."]
      restartPolicy: OnFailure