apiVersion: v1
kind: Pod
metadata:
  name: moja-app-env
  labels:
    app: moja-app
spec:
  containers:
  - name: echo
    image: busybox
    env:
    - name: PRIVITANIE
      value: "Ahoj svet,"
    - name: SPRAVA
      value: "pozdravuje ta"
    - name: MENO
      value: "Kubernetes"
#    command: ["echo"]
#    args: ["$(PRIVITANIE) $(SPRAVA) $(MENO)"]
    command: ["sleep"]
    args: ["100"]
  restartPolicy: OnFailure