apiVersion: v1
kind: Pod
metadata:
  name: moj-dashboard
  labels:
    part: frontend
spec:
  initContainers:
  - name: cloner
    image: alpine/git
    command: 
    - git 
    - clone
    - https://github.com/ColorlibHQ/AdminLTE
    - /var/lib/data
    volumeMounts:
    - mountPath: /var/lib/data
      name: source
  containers:
  - name: presenter
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: source
  volumes:
    - emptyDir: {}
      name: source 
  dnsPolicy: "None"
  dnsConfig:
    nameservers:
    - 8.8.8.8

