apiVersion: v1
kind: Pod
metadata:
  name: moja-app-command
  labels:
    app: moja-app
spec:
  containers:
  - name: echo
    image: busybox
    command: ["echo"]
    args: ["Ahoj svet"]
  restartPolicy: OnFailure