apiVersion: v1
kind: Pod
metadata:
  name: moja-app-affinity
  labels:
    app: moja-app
    part: frontend
spec:
  containers:
  - name: nginx
    image: nginx
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: disk
                operator: In
                values:
                  - ssd
