apiVersion: v1
kind: Pod
metadata:
  name: multicontainer-pod
  labels:
    app: moja-app
    part: frontend
spec:
  volumes:
    - name: html
      emptyDir: {}
  containers:
  - name: prvy
    image: nginx
    volumeMounts:
      - name: html
        mountPath: /usr/share/nginx/html
    ports:
      - containerPort: 80 
  - name: druhy 
    image: debian
    volumeMounts:
      - name: html
        mountPath: /html 
    command: ["/bin/sh", "-c"]
    args:
      - while true; do
          date >> /html/index.html;
          sleep;
        done
