apiVersion: v1
kind: Pod
metadata:
  name: moja-app-taints-eu
  labels:
    app: moja-app
    part: frontend
spec:
  containers:
  - name: nginx
    image: nginx
  tolerations:
    - key: "region"
      operator: "Equal"
      value: "us"
      effect: "NoSchedule"
