apiVersion: v1
kind: ReplicationController
metadata:
  name: moja-app-rc
spec:
  replicas: 3
  selector:
    app: moja-app
    part: frontend
  template:
    metadata:
      name: moja-app-pod
      labels:
        app: moja-app
        part: frontend
    spec:
      containers:
      - name: webserver-container
        image: nginx
        ports:
        - containerPort: 80
