apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: moja-app-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: moja-app
  template:
    metadata:
      name: moja-app-pod
      labels:
        app: moja-app
        part: frontend
    spec:
      containers:
      - name: webserver-container
        image: nginx
        ports:
        - containerPort: 80
