apiVersion: v1
kind: Service
metadata:
  name: moja-service-lb
spec:
  type: LoadBalancer 
  ports:
    - name: http
      protocol: TCP
      targetPort: 80
      port: 8080
      
  selector:
    app: moja-app
