apiVersion: v1
kind: Pod
metadata:
  name: moj-data-pod
  labels:
    app: moja-app
spec:
  containers:
  - name: frontend
    image: nginx
    volumeMounts:
      - mountPath: "/var/www/html" 
        name: frontend-pod
  volumes:
    - name: frontend-pod
      persistentVolumeClaim:
        claimName: moj-pvc
