apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: moj-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  storageClassName: ""
  volumeName: moj-pv
  
